[pytest]
addopts = --alluredir=reports/allure-results -v --tb=short
testpaths = tests

markers =
    smoke: pruebas críticas del sistema
    regression: suite de regresión completa
    elements: pruebas de la sección Elements de DemoQA
    forms: pruebas de la sección Forms de DemoQA
